### ISSUE TITLE
Fails at "make UE4Editor"

### ISSUE THREAD

**Issue by ctogle** [fire/SensibleEditorSourceCodeAccess#10]
athyra@sierpenski-u:~/dev/unreal/UnrealEngine$ make UE4Editor
Engine/Build/BatchFiles/Linux/Build.sh UE4Editor Linux Development 
Building UE4Editor...
Using clang version '3.5.0' (string), 3 (major), 5 (minor), 0 (patch)
/bin/sh  -c '/bin/sh "/home/athyra/dev/unreal/UnrealEngine/Engine/Intermediate/Build/Linux/x86_64-unknown-linux-gnu/UE4Editor/Development/FixDependencies.sh" && touch "/home/athyra/dev/unreal/UnrealEngine/Engine/Intermediate/Build/Linux/x86_64-unknown-linux-gnu/UE4Editor/Development/UE4Editor.link"'
Performing 3 actions (5 in parallel)
[1/3] Compile Module.SensibleEditorSourceCodeAccess.cpp
In file included from /home/athyra/dev/unreal/UnrealEngine/Engine/Intermediate/Build/Linux/x86_64-unknown-linux-gnu/UE4Editor/Development/Plugins/Dynamic/SensibleEditorSourceCodeAccess/Module.SensibleEditorSourceCodeAccess.cpp:2:
In file included from /home/athyra/dev/unreal/UnrealEngine/Engine/Plugins/Developer/SensibleEditorSourceCodeAccess/Source/SensibleEditorSourceCodeAccess/Private/SensibleEditorSourceCodeAccessModule.cpp:24:
In file included from /home/athyra/dev/unreal/UnrealEngine/Engine/Plugins/Developer/SensibleEditorSourceCodeAccess/Source/SensibleEditorSourceCodeAccess/Private/SensibleEditorSourceCodeAccessModule.h:24:
/home/athyra/dev/unreal/UnrealEngine/Engine/Plugins/Developer/SensibleEditorSourceCodeAccess/Source/SensibleEditorSourceCodeAccess/Private/SensibleEditorSourceCodeAccessor.h(30,15) :  error: 'RefreshAvailability' marked 'override' but does not override any member functions
        virtual void RefreshAvailability() override { }
                     ^
1 error generated.
-------- End Detailed Actions Stats -----------------------------------------------------------
ERROR: UBT ERROR: Failed to produce item: /home/athyra/dev/unreal/UnrealEngine/Engine/Plugins/Developer/SensibleEditorSourceCodeAccess/Binaries/Linux/libUE4Editor-SensibleEditorSourceCodeAccess.so
Cumulative action seconds (8 processors): 0.00 building projects, 0.93 compiling, 0.00 creating app bundles, 0.00 generating debug info, 0.00 linking, 0.00 other
UBT execution time: 11.97 seconds
make: *** [UE4Editor] Error 2
athyra@sierpenski-u:~/dev/unreal/UnrealEngine$ 

I don't get the impression I'm doing something incorrectly to cause this, but if so, please let me know!

**Comment by fire** [comment]
What version of the editor are you using?

**Comment by ctogle** [comment]
Under "Help -> About Unreal Editor..." I see this:

Version: 4.7.6-0+++depot+UE4-Releases+4.7

I attempted to git pull earlier today, so I'm under the impression this up
to date. If it helps, I'm running ubuntu.

**Comment by fire** [comment]
You're using a version from several months ago. The current version of Unreal Engine is 4.10.0.

**Comment by fire** [comment]
Any changes on this? Please comment and I'll reopen.
