### ISSUE TITLE
UE4 Can't load module

### ISSUE THREAD

**Issue by markasoftware** [fire/SensibleEditorSourceCodeAccess#11]
I'm getting the following error when attempting to start the UE4 editor with this installed:

    LogModuleManager:Warning: ModuleManager: Unable to load module 'SensibleEditorSourceCodeAccess' because the file '/home/markasoftware/dev/UnrealEngine/Engine/Binaries/Linux/' was not found.

This is in version 4.10 on Arch Linux

**Comment by fire** [comment]
Did you clone this to your UnrealEngine directory at `Engine/Plugins/Developer`?

**Comment by fire** [comment]
Trying to go through the list of things that can go wrong.

**Comment by fire** [comment]
Did you build the engine?

**Comment by markasoftware** [comment]
What I did was I simply cloned it to Engine/Plugins/Developer on an effectively clean installation of UE4. I see the folder there and everything. Do I have to recompile the engine for it to work?

**Comment by fire** [comment]
Yes, you have to recompile the engine.

**Comment by markasoftware** [comment]
Ok, that'll probably fix it. The whole thing, or just the editor? (i.e, can I just run make UE4Editor, or do I have to redo other parts as well)? Maybe this is a stupid question. I've given up using UE4 on Linux anyway due to bugs and stuff, I'm just using it on Windows now.
