### ISSUE TITLE
Unable to load module SensibleEditorSourceCodeAccess

### ISSUE THREAD

**Issue by sunjay** [fire/SensibleEditorSourceCodeAccess#12]
![screenshot from 2016-02-07 10 40 08](https://cloud.githubusercontent.com/assets/530939/12873295/326dff38-cd87-11e5-952a-8acbb086b5eb.png)
![screenshot from 2016-02-07 10 40 14](https://cloud.githubusercontent.com/assets/530939/12873296/326f8628-cd87-11e5-9c6e-60825788bcc1.png)

![screenshot from 2016-02-07 10 40 44](https://cloud.githubusercontent.com/assets/530939/12873300/44156e74-cd87-11e5-8a6e-104f7a2d3097.png)

I'm unable to load this plugin on Linux Mint 17.3. I cloned the plugin into the `Engine/Plugins/Developer` directory. UnrealEngine is compiled into my Downloads directory.

**Comment by fire** [comment]
Did you run the compile the engine command?

**Comment by sunjay** [comment]
I'm not sure what you mean by the compile the engine command. I ran `make`,
`make UE4Editor`, and `./Setup.sh`.

All of them resulted in the same error.

**Comment by fire** [comment]
Can you describe your setup a bit? What version of the engine? I recall that the 4.10 branch is actually 4.11 for some reason. Maybe there's a mixup there.

**Comment by sunjay** [comment]
I'm on Linux Mint 17.3. I cloned the unreal engine 4.11 branch into my
downloads folder and followed the instructions to build it.

I then cloned your plugin and did all the commands I described previously.

**Comment by fire** [comment]
The plugin was not tested for 4.11 as that's a pre-release.

**Comment by sunjay** [comment]
@fire Thanks for your help. I downloaded 4.10 and it seems to compile fine. This is my first time using Unreal Engine, is there some quick way I can check to make sure the plugin has loaded?

**Comment by fire** [comment]
Remember that the Unreal Engine Linux community uses #ue4linux on freenode irc network. It'll be easier to chat.

**Comment by sunjay** [comment]
Thanks! I didn't know about that. I'll ask there.
