### ISSUE TITLE
making the readme.md more usefull

### ISSUE THREAD

**Issue by newincpp** [fire/SensibleEditorSourceCodeAccess#13]
I just wanna say that I expect unreal to compile the plugin automatically and it did not for me so if it happen for other guys it would be awesome if this line:
`mono Engine/Binaries/DotNET/UnrealBuildTool.exe Linux Development UE4Editor -module SensibleEditorSourceCodeAccess`
could appear in the readme =)

**Comment by fire** [comment]
Added, thanks for your suggestion!

**Comment by phcerdan** [comment]
For installation in linux, following https://wiki.unrealengine.com/Linux_Known_Issues :

Add in `Engine/Config/Linux/LinuxEngine.ini`
 [/Script/SourceCodeAccess.SourceCodeAccessSettings]
 PreferredAccessor=SensibleEditorSourceCodeAccessor

and then in the head folder `UnrealEngine`:
`make UE4Editor`

**Comment by fire** [comment]
How does the new readme look?

**Comment by JeremyCooper** [comment]
Looks great, the section about "select-editor" is unclear though.

**Comment by KiloLiuton** [comment]
Hi, I too am confused as to what "select-editor" means. Is it an option inside de UE4 editor?

**Comment by newincpp** [comment]
yeah same, what is "select-editor" ? I tried `find . | grep "select-"` but I get nothing =/
The rest is clear

**Comment by fire** [comment]
https://unix.stackexchange.com/questions/42726/how-do-i-change-the-default-text-editor-in-the-debian-squeeze-distro

**Comment by fire** [comment]
http://manpages.ubuntu.com/manpages/zesty/man1/select-editor.1.html

**Comment by newincpp** [comment]
oh okay I'm on gentoo, that's why I didn't know about it.
on gentoo it's `eselect editor`

**Comment by fire** [comment]
Updated readme.
