### ISSUE TITLE
FSensibleSourceCodeAccessor missing pure virtual AddSourceFiles

### ISSUE THREAD

**Issue by TheSandwichMakr** [fire/SensibleEditorSourceCodeAccess#6]
Does not compile with latest editor because a new method AddSourceFiles is not implemented.
I just added it and made it return true as it seemed that it didn't really care when you add some files, but am hesitant to submit a commit as I know 0 about this.

**Comment by ReedMullanix** [comment]
Same issue here, same fix, except for mine returns false, as do the other plugins provided by epic.

**Comment by fire** [comment]
Closing older issues due to changes in code.
